#!/bin/bash

set -e

( cd examples/git_repository_resource && go test ./... )
( cd examples/hello_world_resource && go test )
( cd examples/k8s_contexts_resources && go test )
( cd examples/list_current_dir_files_tool && go test )
( cd examples/list_k8s_contexts_tool && go test )
( cd examples/streamable_http && go test )
( cd tests/lifecycle && go test )
( go test ./... )

