# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# First stage: Build the Go application
FROM golang:1.20-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o /mcp-server ./examples/list_current_dir_files_tool

# Second stage: Create a small image
FROM alpine:3.18

WORKDIR /

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /mcp-server /mcp-server

# Command to run the executable
ENTRYPOINT ["/mcp-server"]
